apiVersion: v1
kind: Pod
metadata:
  name: <hammerpod>
  namespace: <hammernamespace>
spec:
  containers:
  - name: <hammerpod>
    image: sanran/hammerdb:v4.6-working
    command: 
      - "sleep"
      - "604800"
    resources:
      requests:
        memory: "1G"
        cpu: "1000m"
      limits:
        memory: "1G"
        cpu: "1000m"
    imagePullPolicy: IfNotPresent